### ISSUE TITLE
Default settings

### ISSUE THREAD

**Issue by mlostekk** [roana0229/android-xml-sorter#17]
Is it possible to set the "Where separate prefix" value somehow to 2 as default?

**Comment by roana0229** [comment]
Hi @mlostekk 

Can't set default value now.
If it create a class that inherits `PersistentStateComponent `, it will be possible.
http://www.jetbrains.org/intellij/sdk/docs/basics/persisting_state_of_components.html

But, I can't use the time on maintenance. Sorry.
If possible, please send pull request. 🙏
