### ISSUE TITLE
[FEATURE] Add hook on VCS commit. Group by translatable.

### ISSUE THREAD

**Issue by DevDengChao** [roana0229/android-xml-sorter#22]
I'm using this nice plugin these days, and wonder if this action could be automatically performed when I commit changes on xml files.
And I added some string resources marked as `translatable="false"`, can it group those string form others ?

Well, I know a little bit about IDEA's plugin development, maybe someday I'll send you a pull request.

**Comment by roana0229** [comment]
👀  Thanks!
