### ISSUE TITLE
Assigning a keyboard shortcut raises EmptyThrowable

### ISSUE THREAD

**Issue by mannodermaus** [roana0229/android-xml-sorter#3]
I assigned a keyboard shortcut to the "Sort Xml By Name" action (`^L`, to be exact), so that I can execute it faster. However, every invocation of the action using the shortcut triggers an `EmptyThrowable`:

```
10:20:42 Plugin Error: AndroidXmlSorter threw an uncaught EmptyThrowable. Disable Plugin
10:20:42 EmptyThrowable: cannot share data context between Swing events; initial event count = 117962; current event count = 118157
```

The action still completes successfully, and I see that my XML was indeed sorted, but there is a popup message indicating the error.

**Comment by roana0229** [comment]
Thanks for your report. I confirmed this issue.
I examine the cause of this.

**Comment by mannodermaus** [comment]
Thank you for the quick response! Great work. Looking forward to becoming more productive using this plugin!

**Comment by roana0229** [comment]
Thank you! :+1:
